title: La page personnelle de Yutong HOU
page-top-title: La page personnelle de Yutong HOU
top-section-bg-text: Bienvenue sur la page personnelle de Yutong HOU !
home-subtitle: Yutong HOU&nbsp;|&nbsp;侯雨彤
copyright-text: '&copy; Yutong HOU 2025-2035. Tous droits réservés.'